import type { Scene } from '../engine/types';

// Capítulo 2 — Donostiako portua.
// Nivel A1/A2. Aventura propiamente dicha empieza. NPC: marinera vieja
// que conoció al abuelo. Vocab: lugares, comida básica, números/horas,
// preguntas-respuestas. Trama: marinera entrega un objeto y dice dónde
// está la siguiente página del libro.

export const sceneDonostia: Scene = {
  id: 'ch02-donostia',
  chapter: 2,
  title: 'Donostiako portua',
  subtitle: 'El puerto que recordaba al abuelo',
  level: 'a2',
  bgId: 'donostia-portua',
  intro: {
    title: 'Donostiako portua',
    subtitle: 'Capítulo 2 · Junto al mar',
    body:
      'Has llegado a la bahía de la Concha al amanecer. El olor a sal te golpea antes que cualquier saludo. En el muelle, una mujer mayor remienda redes con paciencia mecánica.\n\nEn la primera página del libro, aitona escribió un nombre: Mirentxu. Y junto a él, un dibujo torpe de un anzuelo.',
  },
  playable: true,
  beats: [
    { type: 'narration', text: 'La bahía está plana como un cristal. Las gaviotas chillan sobre los mástiles. Hueles algas, brea, café de termo.' },
    { type: 'narration', text: 'Una mujer de unos setenta años repara una red. Te mira sin levantar las manos.' },
    { type: 'enter-actor', actor: { id: 'marinela', spriteId: 'marinela', x: 60, y: 70, scale: 2 } },
    {
      type: 'speak',
      speaker: 'Mirentxu',
      spriteId: 'marinela',
      eu: 'Egun on. Galduta zabiltza?',
      es: 'Buenos días. ¿Andas perdido?',
      emotion: 'neutral',
    },
    {
      type: 'choice',
      prompt: 'Tienes que presentarte.',
      options: [
        { label: '"Egun on. Anderren biloba naiz." (Buenos días. Soy nieto/a de Ander.)', gotoLabel: 'reveal-grandson' },
        { label: '"Kaixo. Ez dakit asko, baina ikasten ari naiz." (Hola. No sé mucho, pero estoy aprendiendo.)', gotoLabel: 'reveal-learner' },
      ],
    },
    { type: 'label', id: 'reveal-grandson' },
    {
      type: 'speak',
      speaker: 'Mirentxu',
      spriteId: 'marinela',
      eu: 'Ander zaharrarena? Hura mutil ona zen. Aspaldikoa.',
      es: 'Del viejo Ander? Aquel era un buen chico. De hace mucho.',
      emotion: 'sad',
    },
    { type: 'goto-label', label: 'continue-talk' },
    { type: 'label', id: 'reveal-learner' },
    {
      type: 'speak',
      speaker: 'Mirentxu',
      spriteId: 'marinela',
      eu: 'Hori da hasiera. Beti hala da. Eta nor zara, bada?',
      es: 'Eso es el principio. Siempre lo es. ¿Y quién eres, pues?',
      emotion: 'neutral',
    },
    {
      type: 'speak',
      speaker: 'Tú',
      spriteId: 'biloba',
      eu: 'Anderren biloba naiz.',
      es: 'Soy nieto/a de Ander.',
      emotion: 'neutral',
    },
    {
      type: 'speak',
      speaker: 'Mirentxu',
      spriteId: 'marinela',
      eu: 'A, hura zen mutila... Aspaldikoa.',
      es: 'Ah, aquel era un chico... De hace mucho.',
      emotion: 'sad',
    },
    { type: 'label', id: 'continue-talk' },
    {
      type: 'speak',
      speaker: 'Mirentxu',
      spriteId: 'marinela',
      eu: 'Eta zer behar duzu nigandik?',
      es: '¿Y qué necesitas de mí?',
      emotion: 'neutral',
    },
    {
      type: 'choice',
      prompt: 'Le tiendes el libro. Está cerrado por una cinta de cuero. ¿Qué le dices?',
      options: [
        { label: '"Liburu hau aitonarena zen. Zer da?" (Este libro era del abuelo. ¿Qué es?)', gotoLabel: 'about-book' },
        { label: '"Mapa honetan, zure izena dago." (En este mapa, está su nombre.)', gotoLabel: 'about-map' },
      ],
    },
    { type: 'label', id: 'about-book' },
    {
      type: 'speak',
      speaker: 'Mirentxu',
      spriteId: 'marinela',
      eu: 'Hori liburua da, bai. Baina liburu hau ez da liburu bat. Hori bidea da.',
      es: 'Eso es un libro, sí. Pero este libro no es un libro. Eso es un camino.',
      emotion: 'mystic',
    },
    { type: 'goto-label', label: 'mid-conversation' },
    { type: 'label', id: 'about-map' },
    {
      type: 'speak',
      speaker: 'Mirentxu',
      spriteId: 'marinela',
      eu: 'Bai, banekien etorriko zinela. Ander zaharrak hala esan zidan.',
      es: 'Sí, sabía que vendrías. El viejo Ander me lo dijo.',
      emotion: 'mystic',
    },
    { type: 'label', id: 'mid-conversation' },
    {
      type: 'speak',
      speaker: 'Mirentxu',
      spriteId: 'marinela',
      eu: 'Lagunduko dizut. Baina lehenengo, jakin nahi dut zenbat dakizun.',
      es: 'Te ayudaré. Pero primero, quiero saber cuánto sabes.',
      emotion: 'neutral',
    },
    {
      type: 'puzzle',
      puzzle: {
        type: 'multiple-choice',
        prompt: 'Mirentxu te pregunta la hora para ver si sabes los números. ¿Qué hora son las 8 de la mañana?',
        promptEu: 'Zer ordu da goizean (8:00)?',
        options: [
          'Goizeko zortziak dira.',
          'Arratsaldeko zortziak dira.',
          'Gaueko zortziak dira.',
          'Eguerdiko hamabiak dira.',
        ],
        correctIndex: 0,
        explainCorrect: '"Goizeko" = de la mañana. Ese es el matiz que separa el reloj real del reloj imaginario.',
        explainWrong: 'No es esa parte del día.',
      },
      onSuccess: 'after-time',
    },
    { type: 'label', id: 'after-time' },
    {
      type: 'gain-word',
      word: { eu: 'goiza', es: 'la mañana', level: 'a1' },
    },
    {
      type: 'gain-word',
      word: { eu: 'arratsaldea', es: 'la tarde', level: 'a1' },
    },
    {
      type: 'gain-word',
      word: { eu: 'zortziak', es: 'las ocho', level: 'a1' },
    },
    {
      type: 'speak',
      speaker: 'Mirentxu',
      spriteId: 'marinela',
      eu: 'Ondo. Orain, gose zara? Kafea hartu nahi al duzu?',
      es: 'Bien. ¿Tienes hambre? ¿Quieres un café?',
      emotion: 'happy',
    },
    {
      type: 'choice',
      prompt: 'Te invita a un pintxo y un café. ¿Cómo respondes?',
      options: [
        { label: '"Bai, mesedez. Esnedun kafe bat." (Sí, por favor. Un café con leche.)', gotoLabel: 'accept-coffee' },
        { label: '"Eskerrik asko, baina ez. Banoa." (Gracias, pero no. Me marcho.)', gotoLabel: 'refuse-coffee' },
      ],
    },
    { type: 'label', id: 'accept-coffee' },
    {
      type: 'speak',
      speaker: 'Mirentxu',
      spriteId: 'marinela',
      eu: 'Ona. Eseri hemen. Itsasoari begira.',
      es: 'Bien. Siéntate aquí. Mira al mar.',
      emotion: 'happy',
    },
    { type: 'narration', text: 'Os sentáis en un banco de madera frente a la bahía. Ella saca dos termos.' },
    { type: 'goto-label', label: 'sit-down' },
    { type: 'label', id: 'refuse-coffee' },
    {
      type: 'speak',
      speaker: 'Mirentxu',
      spriteId: 'marinela',
      eu: 'Ez? Ondo. Baina geratu pixka bat. Zerbait kontatu behar dizut.',
      es: '¿No? Bien. Pero quédate un poco. Tengo que contarte algo.',
      emotion: 'neutral',
    },
    { type: 'label', id: 'sit-down' },
    {
      type: 'speak',
      speaker: 'Mirentxu',
      spriteId: 'marinela',
      eu: 'Ander zaharrak ez zuen euskara ahaztu. Baina ezkutatu zuen, urte askotan.',
      es: 'El viejo Ander no olvidó el euskera. Pero lo escondió, durante muchos años.',
      emotion: 'sad',
    },
    {
      type: 'speak',
      speaker: 'Mirentxu',
      spriteId: 'marinela',
      eu: 'Garai haietan, hizkuntza honek arazoak ekartzen zituen. Ulertzen?',
      es: 'En aquellos tiempos, esta lengua traía problemas. ¿Lo entiendes?',
      emotion: 'neutral',
    },
    {
      type: 'speak',
      speaker: 'Mirentxu',
      spriteId: 'marinela',
      eu: 'Baina barruan gorde zuen. Eta bere bilobari eman dio orain. Zuri.',
      es: 'Pero la guardó dentro. Y se la ha dado a su nieto/a ahora. A ti.',
      emotion: 'mystic',
    },
    { type: 'narration', text: 'Saca de su delantal un anzuelo de plata viejo, con una espiral grabada.' },
    {
      type: 'gain-item',
      item: { id: 'anzuelo', name: 'Anzuelo de plata', description: 'Tiene una espiral grabada. Mirentxu dice que perteneció al abuelo y que vale para una sola pregunta a Mari.', icon: '🪝' },
      flavor: 'Mirentxu te lo deja en la mano sin ceremonia.',
    },
    {
      type: 'speak',
      speaker: 'Mirentxu',
      spriteId: 'marinela',
      eu: 'Hurrengo geltokia: Anbotoko mendia. Mari han bizi da. Eta Marik beti galdetzen du.',
      es: 'Siguiente parada: el monte Anboto. Allí vive Mari. Y Mari siempre pregunta.',
      emotion: 'mystic',
    },
    {
      type: 'speak',
      speaker: 'Mirentxu',
      spriteId: 'marinela',
      eu: 'Galderak prestatu behar dituzu. Ez ahaztu: Marik gezurra ezin du jasan.',
      es: 'Tienes que preparar las preguntas. No olvides: Mari no soporta la mentira.',
      emotion: 'neutral',
    },
    { type: 'narration', text: 'Antes de irte, Mirentxu quiere comprobar una cosa más. Dice algo de los días de la semana.' },
    {
      type: 'puzzle',
      puzzle: {
        type: 'fill-in',
        prompt: '"Hoy es martes" en euskera:',
        before: 'Gaur ',
        after: ' da.',
        accept: ['asteartea', 'Asteartea'],
        hint: 'Aste = semana, arte = entre',
      },
      onSuccess: 'after-day',
    },
    { type: 'label', id: 'after-day' },
    {
      type: 'gain-word',
      word: { eu: 'gaur', es: 'hoy', level: 'a1' },
    },
    {
      type: 'gain-word',
      word: { eu: 'asteartea', es: 'martes', level: 'a1' },
    },
    {
      type: 'speak',
      speaker: 'Mirentxu',
      spriteId: 'marinela',
      eu: 'Ondo. Mari prest izango zaitu. Joan zaitez orain.',
      es: 'Bien. Mari estará lista para ti. Vete ahora.',
      emotion: 'neutral',
    },
    {
      type: 'puzzle',
      puzzle: {
        type: 'order-words',
        prompt: 'Construye la frase: "Voy al monte Anboto"',
        words: ['Anbotoko', 'banoa', 'mendira'],
        correctOrder: [1, 0, 2],
      },
      onSuccess: 'goodbye',
    },
    { type: 'label', id: 'goodbye' },
    {
      type: 'speak',
      speaker: 'Tú',
      spriteId: 'biloba',
      eu: 'Eskerrik asko, Mirentxu. Banoa Anbotoko mendira.',
      es: 'Gracias, Mirentxu. Voy al monte Anboto.',
      emotion: 'neutral',
    },
    {
      type: 'speak',
      speaker: 'Mirentxu',
      spriteId: 'marinela',
      eu: 'Eta gogoratu, biloba: hitzak biziak dira.',
      es: 'Y recuerda, nieto/a: las palabras están vivas.',
      emotion: 'mystic',
    },
    { type: 'leave-actor', actorId: 'marinela' },
    { type: 'narration', text: 'El sol está alto. La carretera al interior se mete entre montes. Anboto se ve, lejos, como un diente de piedra.' },
    { type: 'goto-scene', scene: 'ch03-anboto' },
  ],
};
