import type { Scene } from '../engine/types';

// Capítulo 3 — Anbotoko mendia. Encuentro con Mari, diosa montañesa.
// Versión preliminar: encuentro core + 2 puzzles + transición. Nivel B1.

export const sceneAnboto: Scene = {
  id: 'ch03-anboto',
  chapter: 3,
  title: 'Anbotoko mendia',
  subtitle: 'La diosa que te mira desde la cumbre',
  level: 'b1',
  bgId: 'anbotoko-mendia',
  intro: {
    title: 'Anbotoko mendia',
    subtitle: 'Capítulo 3 · La cumbre',
    body:
      'Subes durante tres horas. Cuando llegas a la cumbre, el viento se detiene de golpe. Una mujer está sentada al borde del precipicio, peinándose el pelo rojo con una rama de saúco.\n\nNo te oye llegar. Pero sabe que estás ahí.',
  },
  playable: true,
  beats: [
    { type: 'narration', text: 'El viento ya no sopla. Como si alguien hubiera dado una orden y la naturaleza obedeciera.' },
    { type: 'enter-actor', actor: { id: 'mari', spriteId: 'mari', x: 50, y: 65, scale: 2.4 } },
    {
      type: 'speak',
      speaker: 'Mari',
      spriteId: 'mari',
      eu: 'Bazenekien noiz iritsiko zinen. Baina ez nekien zer galdetuko zenuen.',
      es: 'Sabía cuándo llegarías. Pero no sabía qué preguntarías.',
      emotion: 'mystic',
    },
    {
      type: 'speak',
      speaker: 'Mari',
      spriteId: 'mari',
      eu: 'Ander zaharrak hitzartu zuen kontaketa hau. Berak ere eman zidan amuzkia.',
      es: 'El viejo Ander pactó este relato. Él también me dio el anzuelo.',
      emotion: 'neutral',
    },
    {
      type: 'speak',
      speaker: 'Mari',
      spriteId: 'mari',
      eu: 'Galdera bat egin diezadakezu. Bakar bat. Erantzungo dut. Eta gero, joango zara.',
      es: 'Puedes hacerme una pregunta. Solo una. Responderé. Y luego, te marcharás.',
      emotion: 'mystic',
    },
    {
      type: 'choice',
      prompt: 'Tienes el anzuelo de plata. ¿Qué le preguntas a Mari?',
      options: [
        { label: '"¿Quién es Hitz Beltza?"', gotoLabel: 'q-blackword' },
        { label: '"¿Por qué me ha tocado esto a mí?"', gotoLabel: 'q-why-me' },
        { label: '"¿Aitona sabía que iba a morir?"', gotoLabel: 'q-grandfather' },
      ],
    },
    { type: 'label', id: 'q-blackword' },
    {
      type: 'speak',
      speaker: 'Mari',
      spriteId: 'mari',
      eu: 'Hitz Beltza ez da pertsona bat. Ahozten ez den hitza da.',
      es: 'La Palabra Negra no es una persona. Es la palabra que no se pronuncia.',
      emotion: 'mystic',
    },
    {
      type: 'speak',
      speaker: 'Mari',
      spriteId: 'mari',
      eu: 'Hizkuntza bat hilda dagoenean, Hitz Beltzak janda dago. Eta zuk gelditu behar duzu.',
      es: 'Cuando una lengua muere, está devorada por la Palabra Negra. Y tú tienes que detenerla.',
      emotion: 'sad',
    },
    { type: 'goto-label', label: 'after-question' },
    { type: 'label', id: 'q-why-me' },
    {
      type: 'speak',
      speaker: 'Mari',
      spriteId: 'mari',
      eu: 'Galdera txarra. Baina erantzungo dizut: ez zaizu tokatu. Aukeratu duzu, oraintxe, etortzean.',
      es: 'Mala pregunta. Pero te responderé: no te ha tocado. Has elegido, justo ahora, al venir.',
      emotion: 'neutral',
    },
    { type: 'goto-label', label: 'after-question' },
    { type: 'label', id: 'q-grandfather' },
    {
      type: 'speak',
      speaker: 'Mari',
      spriteId: 'mari',
      eu: 'Bazekien. Hori da gauza zailena: jakitea eta isiltzea.',
      es: 'Lo sabía. Eso es lo más difícil: saber y callar.',
      emotion: 'sad',
    },
    {
      type: 'speak',
      speaker: 'Mari',
      spriteId: 'mari',
      eu: 'Ez zion inori esan. Ezta zuri ere.',
      es: 'No se lo dijo a nadie. Ni siquiera a ti.',
      emotion: 'neutral',
    },
    { type: 'label', id: 'after-question' },
    {
      type: 'speak',
      speaker: 'Mari',
      spriteId: 'mari',
      eu: 'Orain galdera bat egingo dizut nik. Erantzun, eta utziko dizut joaten.',
      es: 'Ahora te haré yo una pregunta. Responde, y te dejaré marchar.',
      emotion: 'mystic',
    },
    {
      type: 'puzzle',
      puzzle: {
        type: 'multiple-choice',
        prompt: 'Mari pregunta: "Si está nublado y hace frío, ¿cómo lo dirías en euskera?"',
        promptEu: 'Lainotuta dago eta hotz egiten du. Nola esaten duzu?',
        options: [
          'Hodeitsu dago eta hotz egiten du.',
          'Eguzkitsu dago eta beroa egiten du.',
          'Atertu du eta epeltzen ari da.',
          'Edertasun handia dago.',
        ],
        correctIndex: 0,
        explainCorrect: 'Hodeitsu / lainotuta = nublado. Hotza = frío.',
      },
      onSuccess: 'after-weather',
    },
    { type: 'label', id: 'after-weather' },
    {
      type: 'gain-word',
      word: { eu: 'lainotuta', es: 'nublado', level: 'b1' },
    },
    {
      type: 'gain-word',
      word: { eu: 'hotza', es: 'el frío', level: 'a1' },
    },
    {
      type: 'speak',
      speaker: 'Mari',
      spriteId: 'mari',
      eu: 'Ondo. Hartu liburuko hurrengo orria. Nik idatzi nuen, urte askoan.',
      es: 'Bien. Toma la siguiente hoja del libro. La escribí yo, hace muchos años.',
      emotion: 'neutral',
    },
    {
      type: 'gain-item',
      item: { id: 'page-mari', name: 'Página de Mari', description: 'Una hoja del libro, ahora legible. Habla del agua y de la memoria.', icon: '📄' },
    },
    {
      type: 'speak',
      speaker: 'Mari',
      spriteId: 'mari',
      eu: 'Hurrengoan, Bilbora. Han ez naiz nor. Han Hitz Beltzak indar handiagoa du.',
      es: 'Después, a Bilbao. Allí no soy nadie. Allí la Palabra Negra tiene más fuerza.',
      emotion: 'sad',
    },
    { type: 'leave-actor', actorId: 'mari' },
    { type: 'narration', text: 'El viento vuelve. Bajas el monte despacio. La página que llevas pesa más de lo que debería.' },
    { type: 'goto-scene', scene: 'ch04-bilbao' },
  ],
};
